### ISSUE TITLE
question regaring sampled values

### ISSUE THREAD

**Issue by robiUser2** [robidev/iec61850_open_server#11]
Hello, I have no issue but only a question: I run this project in a VM. Is it possible to see the SV stream from the web client in wireshark on the VM?

**Comment by robidev** [comment]
Hello, I'm not sure what you mean by sampled value stream from the
web-client. There are no sampled values coming from the web client, or
visualized in the web client. The web client uses reports and polling via
iec61850/mms to display measurements from the ieds.

In the project are 4 ied's, each in a separate docker container, but may be
run on a separate host/vm as well(this requires manual setup). One of these
ied's publishes sampled values, that are subscribed to by another ied(in a
separate container, or on a separate host/vm if desired). By capturing
sampled values on the docker interface, you can see them in wireshark, or
if you decide to run it on a separate host/vm, you can capture it on that
interface.

I hope that answers your question,

Best regards

Op wo 3 apr 2024 14:09 schreef robiUser2 ***@***.***>:

**Comment by robiUser2** [comment]
Hello, is IED3 the sampled values publisher? Sorry, I am very new to docker. What are the steps I need to do to access the docker interface of the publishing ied? Up to now I only installed the open source project following the explanations inside a Ubuntu VM. It is running successfully. What I want to do is: receiving the sampled values on my local Windows PC. Best regards

**Comment by robidev** [comment]
Sure, no problem. Correct, the IED3 is the publisher. If you have the
docker-compose  project running in a local ubuntu VM, you can start
wireshark on the ubuntu VM with root privileges(sudo wireshark), and
capture on 'any' interfaces.  *To get the traffic, you do need to first
start the simulation. I suspect this is where you struggled. *You do this
by first pressing 'open simulation tab', and in the new browser window, you
wait until it indicates ''init ok', and then you press the 'play' button.
When you then start a capture, you should be able to see sampled values. In
hindsight, the fact you need to press play in the simulation to get the
sampled values is not obvious, and it is expected that the simulator starts
automatically when you start the environment. I will update the readme to
reflect that, to make it more clear.

Then you should be able to see the sampled value traffic in wireshark.
Specifically, you can see some interfaces in wireshark that are named
"vethxxxxxxxx", where xxxxxxx is a random string of numbers and/or letters.
any of those interfaces will capture only the sampled value traffic within
the container network.

Best regards,

Robin

**Comment by robiUser2** [comment]
Hello,
thanks a lot for your help. In fact my problem was not with running the simulation (init ok, play button etc. I had) but it was only the "sudo wireshark" command I did not use but instead started wireshark manually with double-click. I assume I had no root priviledges. No I get the sampled value streams "vethxxx".

**Comment by robiUser2** [comment]
Sorry to bother you again. I run the VM in bridge mode. The VM network adapter and the local ethernet which is physically connected to a router do all 3 have ip in the same network 192.168.178.xxx. From the VM I can ping the router. How do I get access with my local wireshark to the sampled value stream which I can see in wireshark inside the VM? Which ip range do I have to set? I tried with 10.0.0.xxx but then I could not ping the router anymore. Please refer also to the screenshots. 
![wireshark_interfaces_inside_VM](https://github.com/robidev/iec61850_open_server/assets/165810248/bf07d018-6138-4ada-9399-74452bc0d50e)
![wireshark_interfaces_local_PC_brideg are VMnet8 and ethernet 4](https://github.com/robidev/iec61850_open_server/assets/165810248/35d454de-d91d-4ac4-8207-24332433eaf1)

**Comment by robidev** [comment]
Hi,

I have not tried that specific setup myself, so am not sure what is
guaranteed to work. I see 2 options;

1 is to modify the container to use macvlan to route layer 2 traffic to a
physical interface. Here is a link that might help:
https://hicu.be/docker-networking-macvlan-bridge-mode-configuration

Option 2 is to run the open server on the host itself instead of in a
container. That means building the open-server program on the (ubuntu)
host, following the instructions in the Readme, and then start the program.
See local_test.sh for an example how to start one or more servers on the
host. By using the L command-line switch instead of R, you can have sampled
values without also having to run and connect the whole simulation
interface.

Hope that helps.

Best regards,

Robin

Op za 6 apr 2024 13:20 schreef robiUser2 ***@***.***>:

**Comment by robiUser2** [comment]
We tried option 2. We used the commands (update+ git clone + cmake + make + cp) out of "Dockerfile.libiec61850_server" to build the open-server program on the host. Then we linked the lib: export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH. Currently we only run "./open_server ens33 9102 cfg/IED3_SMV.cfg cfg/IED3_SMV.ext L 65002 " in the local_test.sh. The project is running like this: 
![image](https://github.com/robidev/iec61850_open_server/assets/165810248/d9dfff7c-8a37-4ce9-8bad-35ff4a19f2ab)
The SV stream is now received outside of the model. But it seams to have no values inside it. I think the reason for this is that the simulation is not on because I only run IED3_SMV and not the simulator. How can I add the simulator to local_test.sh? Currently I cannot start the webbrowser on the host.

**Comment by robiUser2** [comment]
Which parts of the model do I need to really get content in the SV stream of IED3 and how can I add this? Any tipps from your side?

**Comment by robidev** [comment]
Sure,

You're almost there. The screenshot shows the local sample value plugin
config not being loaded. This is due to the following file:
plugin/local_sample_simulator.config.off, please rename this file to
plugin/local_sample_simulator.config so remove the ".off", then the file
should be loaded, and you can define phase, amplitude and frequency per
phase for those elements. I think that should be enough to get it to work.

Best regards,

Robin

**Comment by robiUser2** [comment]
Hi Robin,
meanwhile we tried out macvlan connection but was difficult and unsuccessful at the end. So we continued with installing circuit simulator following the instructions in the readme on local Ubuntu host. The local_test.sh is running, then we carry out python3 webAPI.py (which works) but errors occure once the webbrowser is initiating... I never get further than initiating (not starting, running etc.). The following messages occur:
![image](https://github.com/robidev/iec61850_open_server/assets/165810248/e5c71ec3-214d-4b86-97d7-b214c3173889)
![image](https://github.com/robidev/iec61850_open_server/assets/165810248/02f45832-a1f4-4e22-b0bf-c97ae34cee05)

Before trying this, we also tried your advice and removed the "off" from local_sample_simulator.config. It gets better but there are still error messages there. Could you help us with these?:
![image](https://github.com/robidev/iec61850_open_server/assets/165810248/4ffc3adc-2384-4fa5-9ef2-339668e26572)
![image](https://github.com/robidev/iec61850_open_server/assets/165810248/db33b877-9acd-4112-9ba1-04d8a53943ec)
127.0.0.1:5010 is unable to connect. I read the sampled values into our software on the local Windows PC. We receive the sample value count but currents and voltages are 0. We did not change the content of local_sample_simulator.config. To us it´s only important to get the values, no need to adjust phase angle, amplitude, frequency. 
Best regards

**Comment by robidev** [comment]
Hello,

The things you are trying to do can work, but require you to delve into the
project a bit to understand how things are put together. As you provide not
much information about your goal or knowledge level of iec61850, c or
python, It is difficult to anticipate on the steps you are taking. The
first screenshots indicate the simulator cannot connect to ip addresses
that are most probably regarding the ip's in the containers. If you want
that to work, you do need to modify the SCL file, so that the simulator can
connect to the ip-addreses of the servers you run locally. so it may be the
ip is 127.0.0.1 for all IED's, and different ports for each IED to avoid
conflicts.

Similar issue exists for the web-interface. This interface uses the .svg
file to know what IED's reside on what ip/port combination. this can be
seen by opening the SVG with a text editor, and see entries in the format
of iec61850://[IP]:[port]. those will need to match anything you would like
to connect to. So if you want the web-interface to do anything, you need to
change those accordingly.

For the 3rd and 4th screenshot, you can see the local sample value config
cannot find the expected model, so it will not attach any simulation. You
did not indicate the IED you are starting. If you use the default
local_test.sh, it will be PROT_RELAIS.cfg and .ext. That will not work, as
the local sample_value simulator config expects IED3_SMVMUnn(this can be
seen if you open the .config file). So you need to uncomment ./open_server
lo 9102 cfg/IED3_SMV.cfg cfg/IED3_SMV.ext L 65002 &, and comment out/remove
the ./open_server lo 7102 cfg/PROT_RELAIS.cfg cfg/PROT_RELAIS.ext L 65002
line.

Best regards,

Robin

**Comment by robiUser2** [comment]
Hello Robin,
I am an engineer and am working together with a software developer on this topic. I also find it difficult to describe in written form what we did. Trying to describe the steps we did more in detail here:

This is our ip config:
![image](https://github.com/robidev/iec61850_open_server/assets/165810248/485ed064-961f-4ce2-8e9f-88e3550fa3a1)
I use local_test.sh
![image](https://github.com/robidev/iec61850_open_server/assets/165810248/1dd2b1a7-1299-48b3-aa89-2b8d77c71ac5)
I changed the IPs in the SCD to this for all 4 IEDs:
![image](https://github.com/robidev/iec61850_open_server/assets/165810248/081f196f-1f37-4b74-9366-26a8e3c9a93b)
We start the open_server locally like this:
![image](https://github.com/robidev/iec61850_open_server/assets/165810248/48f5ec74-14c1-47aa-af16-cddf02535a2d)
![image](https://github.com/robidev/iec61850_open_server/assets/165810248/3c945bea-7e62-4621-9f65-6eba51cd653b)
![image](https://github.com/robidev/iec61850_open_server/assets/165810248/7339c9b1-7149-4fae-82ec-8ae51239159e)
What would be the next step to fix the error message "could not find logical node object ref: IED3_SMVMUnn"?

Do we need to install the iec61850_open_client also locally? My understanding is that we need to access the webclient and start the simulation to get current and voltage values? If we do not need the client, please ignore this paragraph. We followed your steps in the readme circuit_simulator-> local install. In mmi.local.svg I changed the IPs all to 192.168.209.132 and left the ports as they were. Starting the webAPI after carrying out the steps in local install circuit simulator unfortunately still gives error messages:
![image](https://github.com/robidev/iec61850_open_server/assets/165810248/3975c281-b38e-40d4-921a-30e1d282fd43)
How can I change the ports there? I think it should not be 65000 for IED3 but 65002? I do not find the place where this can be changed. Up to now we did not work on these error messages as long as we don´t know if we need the client locally installed.
![image](https://github.com/robidev/iec61850_open_server/assets/165810248/9f74de46-de4e-4ae8-9da8-10427f1f96b7)
![image](https://github.com/robidev/iec61850_open_server/assets/165810248/9e6f3438-c682-47b6-977e-059ae9a403f4)
Best regards

**Comment by robidev** [comment]
Hello,

If you only need sampled values, you do not need the iec61850_open_client,
that is only a web-client to read out the server via MMS. The circuit
simulation can be started without. The only thing that the web-client does,
is open a new page to a webserver listening on [ip]:5010, based on a
hyperlink in the .svg file; "open simulation tab".

The circuit simulator that listens on port 5010 is used to read out the
substation section of the SCL, build a SPICE electronic model, and couple
the switch status and values from the model to the actual CT/VT elements in
the servers. It assumes port 65000 is used for connecting the circuit
simulator to the ied-instances. So you cannot run mutiple on 1 host, unless
you register multiple IP's to 1 interface. If you do not need the part for
circuit simulation, and just want to simulate some sampled values like you
said. You do not need that part either, and can just not start it. When you
want to connect, the last command-line argument of a server needs to be R,
if you do not want to use the circuit simulator, you should use L.

I see in local_test.sh, you start 2 servers. This makes it difficult to
read the log-output, as the log-messages from both servers are interleaved.
Please comment out the line "./open_server lo 7102 cfg/IED1_XCBR.cfg
cfg/IED1_XCBR.ext R 65000 &", so that only the output of ied3 is provided.
that should help to understand what is going on, and might also resolve the
issue.

Best regards,

Robin

**Comment by robiUser2** [comment]
Hello,
thanks for answering. I use it like this now.
![image](https://github.com/robidev/iec61850_open_server/assets/165810248/beb13d5f-2fff-4da2-ac19-8f77f5b41408)
![image](https://github.com/robidev/iec61850_open_server/assets/165810248/ec82af21-111a-414c-9b3c-1bdc88a6c9c0)
The sampled values are now received on the Windows PC like they should. Many thanks!
![image](https://github.com/robidev/iec61850_open_server/assets/165810248/c967ebac-0850-4b1e-adfb-39a8e548061b)
When reading in the data into our software unfortunately I always only receive the sample value counter but no content inside the currents/voltages. 
Using the local_sample_simulator without changes in the file: should give me some 10A and 20V at 50Hz I thought?
This is how it is received in our software:
![image](https://github.com/robidev/iec61850_open_server/assets/165810248/c2d1cc9c-2773-414c-b746-424ea4cd9376)
![image](https://github.com/robidev/iec61850_open_server/assets/165810248/4c7f5c11-3750-4034-baf1-282083b2e9b3)
Is there any possibility to check if currents/ voltages are sent out?
Best regards,
Katharina

**Comment by robidev** [comment]
Hi,

Ok, yes it seems for some reason the sampled value simulator cannot find
the sampled-value control block. "ERROR: cannot find SMV instance: MSVCB01
in model" is the message that indicates something is still wrong.
Therefore, no values are published. Can you confirm the IED3_SMV.cfg and
IED3_SMV.ext you use are identical with the one on the open_server github
repo?

 It is strange, as I have had this working. It might be there is somewhere
a bug there preventing the SMV instance to be found by the plugin, but I
will have to debug the c-code when I have some time.

Best regards,

Robin

**Comment by robiUser2** [comment]
Hi Robin,
yes, I use IED3_SMV.cfg and IED3_SMV.ext identical to the repo. 
Best regards

**Comment by robidev** [comment]
Hi,

I found the (sily)issue, and pushed a fix. You need to retrieve the latest
version (e.g. 'git pull'), and rebuild the project with 'make'. Then the
error-message "ERROR: cannot find SMV instance: MSVCB01 in model" should
not appear anymore, and the values should not be 0 anymore.

**Comment by robiUser2** [comment]
Hi Robin,
now it works. Many thanks for your help!
