### ISSUE TITLE
Eventlet + DNS Python Attribute Error: module "dns.rdtypes" has no attribute ANY

### ISSUE THREAD

**Issue by JT-simutech** [robidev/iec61850_open_server#8]
The client application fails to start when tested in both Debian image in Google Cloud docker container and on Ubuntu 22.04.2 LTS VM with docker container.  The error message is as shown in attached picture: AttributeError: module 'dns.rdtypes' has no attribute 'ANY'

I tried to add dns:8.8.8.8 in the yaml file, and I tried also to downgrade dnspython to 2.2.1 in the client container but no success.

Link to similar issue: [stackoverflow](https://stackoverflow.com/questions/75137717/eventlet-dns-python-attribute-error-module-dns-rdtypes-has-no-attribute-any) 

![Docker_containers_built](https://github.com/robidev/iec61850_open_server/assets/7595881/a7c45e8e-a2c6-41f1-abdc-0f4d1d0b1311)
![DnsPython_rdtypes_fail](https://github.com/robidev/iec61850_open_server/assets/7595881/390caeb3-a562-464b-b494-5c2a67314d83)

**Comment by robidev** [comment]
Thanks for reporting this. 

The issue is that eventlet seems to cause this now due to DNS resolve loading, while it did not show this issue before when I tested it about 6 month ago. 

Bumping eventlet to version 0.33.3 seems to fix this. Ive updated the repo, or you can modify requirements.txt yourself manually; eventlet==0.33.2 -> eventlet==0.33.3. 

After modifying, you will need to rebuild the container. i.e. 

$ sudo docker-compose -f substation.yml -f substation.simulator.yml build 

Did this resolve your issue?

**Comment by JT-simutech** [comment]
Yes, the issue is now resolved. I re-tested starting client on both VM local and with Google Cloud VM on Ubuntu 22.04. Thank you for your quick response!
